-- ============================================================================
-- 20260726000600_explicit_table_grants.sql
--
-- INTENT: make the schema reproducible. Right now it is not.
--
-- THE PROBLEM, measured rather than argued. Not one of the 31 prior migrations issues a
-- single GRANT on a table. All 26 tables inherit every privilege they have from
-- pg_default_acl -- Supabase's bootstrap `ALTER DEFAULT PRIVILEGES ... GRANT ALL ON TABLES
-- TO anon, authenticated, service_role`. That default is a property of the platform image,
-- not of this repository, and Supabase has since narrowed it.
--
-- What that means was verified end to end, not assumed. A throwaway project on Supabase CLI
-- 2.109.1, all 31 migrations applied from scratch:
--
--     tables                                 26   (correct)
--     policies                               34   (correct)
--     privileges for `authenticated`         REFERENCES, TRIGGER, and the wipe verb
--     tables readable by `authenticated`     0 of 26
--     SELECT titles / organizations / memberships as authenticated
--                                            permission denied, all three
--
-- So rebuilding from migrations produces a structurally perfect and completely non-
-- functional database. Every read 403s. SECURITY DEFINER RPCs still execute (they run as
-- owner), so writes appear to work while nothing can be read back -- a worse failure than
-- refusing to start, because it presents as an application bug.
--
-- That is the disaster-recovery path and the staging path, not a CI quirk.
--
-- Note the shape of what the newer image kept: REFERENCES, TRIGGER and the wipe verb
-- survive while SELECT/INSERT/UPDATE/DELETE are gone. The residual privileges from finding
-- 2.6 are precisely the ones that persist. 20260726000300 removes those; this migration
-- restores the ones the application actually needs. The two are complementary, and
-- 20260726000300 must run first.
--
-- WHAT THIS GRANTS: exactly the privilege set live production has today, minus the four
-- residuals. Generated by introspecting production/local rather than hand-typed, so
-- applying it to a fresh database reproduces the current production privilege model
-- exactly -- no more, no less. It is deliberately NOT a tightening pass; matching today's
-- behaviour is the point. Narrowing these to precisely what each table's policies admit is
-- a separate, reviewable change.
--
-- `anon` gets nothing. It has no grants in production and none here.
--
-- RLS is unaffected. These are table privileges; the 34 policies still decide every row.
-- A grant here without a matching policy is still a closed door.
--
-- DESTRUCTIVE OPS: none. GRANT only, plus the anon revoke that every prior migration
-- already performs. Idempotent, forward-only.
-- ============================================================================

-- anon: explicitly nothing. Stated so the absence is a decision, not an oversight.
revoke all on all tables in schema public from anon;


-- ----------------------------------------------------------------------------
-- authenticated
-- ----------------------------------------------------------------------------
grant select, insert on public.assets to authenticated;
grant select, insert on public.audit_log to authenticated;
grant select, insert on public.contract_assents to authenticated;
grant select, insert, update, delete on public.contract_terms to authenticated;
grant select on public.deliveries to authenticated;
grant select on public.export_records to authenticated;
grant select on public.findings to authenticated;
grant select, insert, update, delete on public.gc_staff to authenticated;
grant select, insert, update, delete on public.memberships to authenticated;
grant select, insert on public.notification_reads to authenticated;
grant select on public.notifications to authenticated;
grant select, insert, update, delete on public.organizations to authenticated;
grant select on public.portal_access_events to authenticated;
grant select on public.portal_links to authenticated;
grant select on public.portal_otps to authenticated;
grant select on public.portal_sessions to authenticated;
grant select, insert on public.rights_grants to authenticated;
grant select on public.screener_view_events to authenticated;
grant select, insert on public.source_documents to authenticated;
grant select, insert on public.source_records to authenticated;
grant select, insert, update, delete on public.subscriptions to authenticated;
grant select on public.title_metadata to authenticated;
grant select on public.title_reviews to authenticated;
grant select, insert, update, delete on public.titles to authenticated;
grant select, insert, update, delete on public.vendors to authenticated;
grant select on public.works to authenticated;

-- ----------------------------------------------------------------------------
-- service_role
-- ----------------------------------------------------------------------------
grant select, insert on public.assets to service_role;
grant select, insert on public.audit_log to service_role;
grant select, insert on public.contract_assents to service_role;
grant select, insert, update, delete on public.contract_terms to service_role;
grant select on public.deliveries to service_role;
grant select on public.export_records to service_role;
grant select, insert, update, delete on public.findings to service_role;
grant select, insert, update, delete on public.gc_staff to service_role;
grant select, insert, update, delete on public.memberships to service_role;
grant select, insert, update, delete on public.notification_reads to service_role;
grant select, insert, update, delete on public.notifications to service_role;
grant select, insert, update, delete on public.organizations to service_role;
grant select, insert on public.portal_access_events to service_role;
grant select on public.portal_links to service_role;
grant select, insert, update on public.portal_otps to service_role;
grant select, insert on public.portal_sessions to service_role;
grant select, insert on public.rights_grants to service_role;
grant select, insert on public.screener_view_events to service_role;
grant select, insert on public.source_documents to service_role;
grant select, insert on public.source_records to service_role;
grant select, insert, update, delete on public.subscriptions to service_role;
grant select on public.title_metadata to service_role;
grant select on public.title_reviews to service_role;
grant select, insert, update, delete on public.titles to service_role;
grant select, insert, update, delete on public.vendors to service_role;
grant select on public.works to service_role;

-- ----------------------------------------------------------------------------
-- Prove it at apply time. Fails the migration if any table is not readable by
-- `authenticated` -- the exact condition that makes a rebuild useless.
-- ----------------------------------------------------------------------------
do $$
declare v_missing text;
begin
  select string_agg(c.relname, ', ' order by c.relname) into v_missing
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
    and not has_table_privilege('authenticated', c.oid, 'SELECT');
  if v_missing is not null then
    raise exception 'tables not readable by authenticated after explicit grants: %', v_missing;
  end if;
  raise notice 'explicit grants applied; all % tables readable by authenticated',
    (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relkind='r');
end $$;

